apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"cybersec-website"},"name":"cybersec-website-service","namespace":"cybersec-website"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"cybersec-website"},"type":"ClusterIP"}}
    creationTimestamp: "2025-07-07T15:13:50Z"
    labels:
      app: cybersec-website
    name: cybersec-website-service
    namespace: cybersec-website
    resourceVersion: "21642"
    uid: 568106c6-c2e9-48c7-947f-5128c7659ba3
  spec:
    clusterIP: 10.100.233.78
    clusterIPs:
    - 10.100.233.78
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: cybersec-website
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"cybersec-website","version":"v1"},"name":"cybersec-website","namespace":"cybersec-website"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"cybersec-website"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"cybersec-website","version":"v1"}},"spec":{"containers":[{"image":"588402992108.dkr.ecr.ap-south-1.amazonaws.com/skay-cybersec-website:3fd995f8e581f106d35af3542dc330d930024437","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":30,"periodSeconds":10,"timeoutSeconds":5},"name":"website","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":5,"periodSeconds":5,"timeoutSeconds":3},"resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"50m","memory":"64Mi"}}}]}}}}
    creationTimestamp: "2025-07-07T17:01:19Z"
    generation: 3
    labels:
      app: cybersec-website
      version: v1
    name: cybersec-website
    namespace: cybersec-website
    resourceVersion: "44137"
    uid: 6fba9025-a4e5-424b-a439-43ce3303fd5e
  spec:
    progressDeadlineSeconds: 600
    replicas: 0
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: cybersec-website
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cybersec-website
          version: v1
      spec:
        containers:
        - image: 588402992108.dkr.ecr.ap-south-1.amazonaws.com/skay-cybersec-website:3fd995f8e581f106d35af3542dc330d930024437
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: website
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2025-07-07T17:01:29Z"
      lastUpdateTime: "2025-07-07T17:01:29Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-07-07T17:01:19Z"
      lastUpdateTime: "2025-07-07T17:06:43Z"
      message: ReplicaSet "cybersec-website-667fcd8847" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 3
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "0"
      deployment.kubernetes.io/max-replicas: "1"
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2025-07-07T17:06:33Z"
    generation: 3
    labels:
      app: cybersec-website
      pod-template-hash: 667fcd8847
      version: v1
    name: cybersec-website-667fcd8847
    namespace: cybersec-website
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: cybersec-website
      uid: 6fba9025-a4e5-424b-a439-43ce3303fd5e
    resourceVersion: "44135"
    uid: 5c4513d9-a376-4d17-bdd4-1a6974a9f7eb
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: cybersec-website
        pod-template-hash: 667fcd8847
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cybersec-website
          pod-template-hash: 667fcd8847
          version: v1
      spec:
        containers:
        - image: 588402992108.dkr.ecr.ap-south-1.amazonaws.com/skay-cybersec-website:3fd995f8e581f106d35af3542dc330d930024437
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: website
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 3
    replicas: 0
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "2"
      deployment.kubernetes.io/max-replicas: "3"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-07-07T17:01:19Z"
    generation: 3
    labels:
      app: cybersec-website
      pod-template-hash: c9784ff7d
      version: v1
    name: cybersec-website-c9784ff7d
    namespace: cybersec-website
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: cybersec-website
      uid: 6fba9025-a4e5-424b-a439-43ce3303fd5e
    resourceVersion: "40970"
    uid: d80b8c78-bc37-423c-8cfd-a14a24ade508
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: cybersec-website
        pod-template-hash: c9784ff7d
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cybersec-website
          pod-template-hash: c9784ff7d
          version: v1
      spec:
        containers:
        - image: 588402992108.dkr.ecr.ap-south-1.amazonaws.com/skay-cybersec-website:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: website
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 3
    replicas: 0
kind: List
metadata:
  resourceVersion: ""
